/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedStaffIdRouteImport } from './routes/_authenticated/staff.$id'
import { Route as AuthenticatedLeadsIdRouteImport } from './routes/_authenticated/leads.$id'
import { Route as AuthenticatedFinanceSettlementsRouteImport } from './routes/_authenticated/finance.settlements'
import { Route as AuthenticatedFinancePnlRouteImport } from './routes/_authenticated/finance.pnl'
import { Route as AuthenticatedFinancePayrollRouteImport } from './routes/_authenticated/finance.payroll'
import { Route as AuthenticatedFinancePaymentsRouteImport } from './routes/_authenticated/finance.payments'
import { Route as AuthenticatedFinanceInvoicesRouteImport } from './routes/_authenticated/finance.invoices'
import { Route as AuthenticatedFinanceExpensesRouteImport } from './routes/_authenticated/finance.expenses'
import { Route as AuthenticatedFinanceContractsRouteImport } from './routes/_authenticated/finance.contracts'
import { Route as AuthenticatedFinanceCashFlowRouteImport } from './routes/_authenticated/finance.cash-flow'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSubscriptionPlansRouteImport } from './routes/_authenticated/admin.subscription-plans'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminPriceListsRouteImport } from './routes/_authenticated/admin.price-lists'
import { Route as AuthenticatedAdminPaymentMethodsRouteImport } from './routes/_authenticated/admin.payment-methods'
import { Route as AuthenticatedAdminLeadSourcesRouteImport } from './routes/_authenticated/admin.lead-sources'
import { Route as AuthenticatedAdminIncomeCategoriesRouteImport } from './routes/_authenticated/admin.income-categories'
import { Route as AuthenticatedAdminGroupsRouteImport } from './routes/_authenticated/admin.groups'
import { Route as AuthenticatedAdminExpenseCategoriesRouteImport } from './routes/_authenticated/admin.expense-categories'
import { Route as AuthenticatedAdminEmailTemplatesRouteImport } from './routes/_authenticated/admin.email-templates'
import { Route as AuthenticatedAdminDiscountsRouteImport } from './routes/_authenticated/admin.discounts'
import { Route as AuthenticatedAdminContractTemplatesRouteImport } from './routes/_authenticated/admin.contract-templates'
import { Route as AuthenticatedAdminBranchesRouteImport } from './routes/_authenticated/admin.branches'
import { Route as AuthenticatedClientsChildrenIndexRouteImport } from './routes/_authenticated/clients.children.index'
import { Route as AuthenticatedClientsChildrenIdRouteImport } from './routes/_authenticated/clients.children.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffIdRoute = AuthenticatedStaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedLeadsIdRoute = AuthenticatedLeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceSettlementsRoute =
  AuthenticatedFinanceSettlementsRouteImport.update({
    id: '/finance/settlements',
    path: '/finance/settlements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinancePnlRoute = AuthenticatedFinancePnlRouteImport.update({
  id: '/finance/pnl',
  path: '/finance/pnl',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinancePayrollRoute =
  AuthenticatedFinancePayrollRouteImport.update({
    id: '/finance/payroll',
    path: '/finance/payroll',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinancePaymentsRoute =
  AuthenticatedFinancePaymentsRouteImport.update({
    id: '/finance/payments',
    path: '/finance/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceInvoicesRoute =
  AuthenticatedFinanceInvoicesRouteImport.update({
    id: '/finance/invoices',
    path: '/finance/invoices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceExpensesRoute =
  AuthenticatedFinanceExpensesRouteImport.update({
    id: '/finance/expenses',
    path: '/finance/expenses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceContractsRoute =
  AuthenticatedFinanceContractsRouteImport.update({
    id: '/finance/contracts',
    path: '/finance/contracts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceCashFlowRoute =
  AuthenticatedFinanceCashFlowRouteImport.update({
    id: '/finance/cash-flow',
    path: '/finance/cash-flow',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSubscriptionPlansRoute =
  AuthenticatedAdminSubscriptionPlansRouteImport.update({
    id: '/admin/subscription-plans',
    path: '/admin/subscription-plans',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/admin/services',
    path: '/admin/services',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPriceListsRoute =
  AuthenticatedAdminPriceListsRouteImport.update({
    id: '/admin/price-lists',
    path: '/admin/price-lists',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPaymentMethodsRoute =
  AuthenticatedAdminPaymentMethodsRouteImport.update({
    id: '/admin/payment-methods',
    path: '/admin/payment-methods',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLeadSourcesRoute =
  AuthenticatedAdminLeadSourcesRouteImport.update({
    id: '/admin/lead-sources',
    path: '/admin/lead-sources',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIncomeCategoriesRoute =
  AuthenticatedAdminIncomeCategoriesRouteImport.update({
    id: '/admin/income-categories',
    path: '/admin/income-categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminGroupsRoute =
  AuthenticatedAdminGroupsRouteImport.update({
    id: '/admin/groups',
    path: '/admin/groups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminExpenseCategoriesRoute =
  AuthenticatedAdminExpenseCategoriesRouteImport.update({
    id: '/admin/expense-categories',
    path: '/admin/expense-categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmailTemplatesRoute =
  AuthenticatedAdminEmailTemplatesRouteImport.update({
    id: '/admin/email-templates',
    path: '/admin/email-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDiscountsRoute =
  AuthenticatedAdminDiscountsRouteImport.update({
    id: '/admin/discounts',
    path: '/admin/discounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminContractTemplatesRoute =
  AuthenticatedAdminContractTemplatesRouteImport.update({
    id: '/admin/contract-templates',
    path: '/admin/contract-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBranchesRoute =
  AuthenticatedAdminBranchesRouteImport.update({
    id: '/admin/branches',
    path: '/admin/branches',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsChildrenIndexRoute =
  AuthenticatedClientsChildrenIndexRouteImport.update({
    id: '/clients/children/',
    path: '/clients/children/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsChildrenIdRoute =
  AuthenticatedClientsChildrenIdRouteImport.update({
    id: '/clients/children/$id',
    path: '/clients/children/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/contract-templates': typeof AuthenticatedAdminContractTemplatesRoute
  '/admin/discounts': typeof AuthenticatedAdminDiscountsRoute
  '/admin/email-templates': typeof AuthenticatedAdminEmailTemplatesRoute
  '/admin/expense-categories': typeof AuthenticatedAdminExpenseCategoriesRoute
  '/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/admin/income-categories': typeof AuthenticatedAdminIncomeCategoriesRoute
  '/admin/lead-sources': typeof AuthenticatedAdminLeadSourcesRoute
  '/admin/payment-methods': typeof AuthenticatedAdminPaymentMethodsRoute
  '/admin/price-lists': typeof AuthenticatedAdminPriceListsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/subscription-plans': typeof AuthenticatedAdminSubscriptionPlansRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/finance/cash-flow': typeof AuthenticatedFinanceCashFlowRoute
  '/finance/contracts': typeof AuthenticatedFinanceContractsRoute
  '/finance/expenses': typeof AuthenticatedFinanceExpensesRoute
  '/finance/invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/finance/payments': typeof AuthenticatedFinancePaymentsRoute
  '/finance/payroll': typeof AuthenticatedFinancePayrollRoute
  '/finance/pnl': typeof AuthenticatedFinancePnlRoute
  '/finance/settlements': typeof AuthenticatedFinanceSettlementsRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/staff/$id': typeof AuthenticatedStaffIdRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
  '/clients/children/$id': typeof AuthenticatedClientsChildrenIdRoute
  '/clients/children/': typeof AuthenticatedClientsChildrenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/contract-templates': typeof AuthenticatedAdminContractTemplatesRoute
  '/admin/discounts': typeof AuthenticatedAdminDiscountsRoute
  '/admin/email-templates': typeof AuthenticatedAdminEmailTemplatesRoute
  '/admin/expense-categories': typeof AuthenticatedAdminExpenseCategoriesRoute
  '/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/admin/income-categories': typeof AuthenticatedAdminIncomeCategoriesRoute
  '/admin/lead-sources': typeof AuthenticatedAdminLeadSourcesRoute
  '/admin/payment-methods': typeof AuthenticatedAdminPaymentMethodsRoute
  '/admin/price-lists': typeof AuthenticatedAdminPriceListsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/subscription-plans': typeof AuthenticatedAdminSubscriptionPlansRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/finance/cash-flow': typeof AuthenticatedFinanceCashFlowRoute
  '/finance/contracts': typeof AuthenticatedFinanceContractsRoute
  '/finance/expenses': typeof AuthenticatedFinanceExpensesRoute
  '/finance/invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/finance/payments': typeof AuthenticatedFinancePaymentsRoute
  '/finance/payroll': typeof AuthenticatedFinancePayrollRoute
  '/finance/pnl': typeof AuthenticatedFinancePnlRoute
  '/finance/settlements': typeof AuthenticatedFinanceSettlementsRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/staff/$id': typeof AuthenticatedStaffIdRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
  '/clients/children/$id': typeof AuthenticatedClientsChildrenIdRoute
  '/clients/children': typeof AuthenticatedClientsChildrenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRouteWithChildren
  '/_authenticated/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/_authenticated/admin/contract-templates': typeof AuthenticatedAdminContractTemplatesRoute
  '/_authenticated/admin/discounts': typeof AuthenticatedAdminDiscountsRoute
  '/_authenticated/admin/email-templates': typeof AuthenticatedAdminEmailTemplatesRoute
  '/_authenticated/admin/expense-categories': typeof AuthenticatedAdminExpenseCategoriesRoute
  '/_authenticated/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/_authenticated/admin/income-categories': typeof AuthenticatedAdminIncomeCategoriesRoute
  '/_authenticated/admin/lead-sources': typeof AuthenticatedAdminLeadSourcesRoute
  '/_authenticated/admin/payment-methods': typeof AuthenticatedAdminPaymentMethodsRoute
  '/_authenticated/admin/price-lists': typeof AuthenticatedAdminPriceListsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/subscription-plans': typeof AuthenticatedAdminSubscriptionPlansRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/finance/cash-flow': typeof AuthenticatedFinanceCashFlowRoute
  '/_authenticated/finance/contracts': typeof AuthenticatedFinanceContractsRoute
  '/_authenticated/finance/expenses': typeof AuthenticatedFinanceExpensesRoute
  '/_authenticated/finance/invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/_authenticated/finance/payments': typeof AuthenticatedFinancePaymentsRoute
  '/_authenticated/finance/payroll': typeof AuthenticatedFinancePayrollRoute
  '/_authenticated/finance/pnl': typeof AuthenticatedFinancePnlRoute
  '/_authenticated/finance/settlements': typeof AuthenticatedFinanceSettlementsRoute
  '/_authenticated/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/_authenticated/staff/$id': typeof AuthenticatedStaffIdRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
  '/_authenticated/clients/children/$id': typeof AuthenticatedClientsChildrenIdRoute
  '/_authenticated/clients/children/': typeof AuthenticatedClientsChildrenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/overview'
    | '/staff'
    | '/admin/branches'
    | '/admin/contract-templates'
    | '/admin/discounts'
    | '/admin/email-templates'
    | '/admin/expense-categories'
    | '/admin/groups'
    | '/admin/income-categories'
    | '/admin/lead-sources'
    | '/admin/payment-methods'
    | '/admin/price-lists'
    | '/admin/roles'
    | '/admin/services'
    | '/admin/subscription-plans'
    | '/admin/users'
    | '/clients/$id'
    | '/finance/cash-flow'
    | '/finance/contracts'
    | '/finance/expenses'
    | '/finance/invoices'
    | '/finance/payments'
    | '/finance/payroll'
    | '/finance/pnl'
    | '/finance/settlements'
    | '/leads/$id'
    | '/staff/$id'
    | '/clients/'
    | '/leads/'
    | '/clients/children/$id'
    | '/clients/children/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/overview'
    | '/staff'
    | '/admin/branches'
    | '/admin/contract-templates'
    | '/admin/discounts'
    | '/admin/email-templates'
    | '/admin/expense-categories'
    | '/admin/groups'
    | '/admin/income-categories'
    | '/admin/lead-sources'
    | '/admin/payment-methods'
    | '/admin/price-lists'
    | '/admin/roles'
    | '/admin/services'
    | '/admin/subscription-plans'
    | '/admin/users'
    | '/clients/$id'
    | '/finance/cash-flow'
    | '/finance/contracts'
    | '/finance/expenses'
    | '/finance/invoices'
    | '/finance/payments'
    | '/finance/payroll'
    | '/finance/pnl'
    | '/finance/settlements'
    | '/leads/$id'
    | '/staff/$id'
    | '/clients'
    | '/leads'
    | '/clients/children/$id'
    | '/clients/children'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/overview'
    | '/_authenticated/staff'
    | '/_authenticated/admin/branches'
    | '/_authenticated/admin/contract-templates'
    | '/_authenticated/admin/discounts'
    | '/_authenticated/admin/email-templates'
    | '/_authenticated/admin/expense-categories'
    | '/_authenticated/admin/groups'
    | '/_authenticated/admin/income-categories'
    | '/_authenticated/admin/lead-sources'
    | '/_authenticated/admin/payment-methods'
    | '/_authenticated/admin/price-lists'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/subscription-plans'
    | '/_authenticated/admin/users'
    | '/_authenticated/clients/$id'
    | '/_authenticated/finance/cash-flow'
    | '/_authenticated/finance/contracts'
    | '/_authenticated/finance/expenses'
    | '/_authenticated/finance/invoices'
    | '/_authenticated/finance/payments'
    | '/_authenticated/finance/payroll'
    | '/_authenticated/finance/pnl'
    | '/_authenticated/finance/settlements'
    | '/_authenticated/leads/$id'
    | '/_authenticated/staff/$id'
    | '/_authenticated/clients/'
    | '/_authenticated/leads/'
    | '/_authenticated/clients/children/$id'
    | '/_authenticated/clients/children/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/$id': {
      id: '/_authenticated/staff/$id'
      path: '/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof AuthenticatedStaffIdRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/leads/$id': {
      id: '/_authenticated/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AuthenticatedLeadsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/settlements': {
      id: '/_authenticated/finance/settlements'
      path: '/finance/settlements'
      fullPath: '/finance/settlements'
      preLoaderRoute: typeof AuthenticatedFinanceSettlementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/pnl': {
      id: '/_authenticated/finance/pnl'
      path: '/finance/pnl'
      fullPath: '/finance/pnl'
      preLoaderRoute: typeof AuthenticatedFinancePnlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/payroll': {
      id: '/_authenticated/finance/payroll'
      path: '/finance/payroll'
      fullPath: '/finance/payroll'
      preLoaderRoute: typeof AuthenticatedFinancePayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/payments': {
      id: '/_authenticated/finance/payments'
      path: '/finance/payments'
      fullPath: '/finance/payments'
      preLoaderRoute: typeof AuthenticatedFinancePaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/invoices': {
      id: '/_authenticated/finance/invoices'
      path: '/finance/invoices'
      fullPath: '/finance/invoices'
      preLoaderRoute: typeof AuthenticatedFinanceInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/expenses': {
      id: '/_authenticated/finance/expenses'
      path: '/finance/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof AuthenticatedFinanceExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/contracts': {
      id: '/_authenticated/finance/contracts'
      path: '/finance/contracts'
      fullPath: '/finance/contracts'
      preLoaderRoute: typeof AuthenticatedFinanceContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/cash-flow': {
      id: '/_authenticated/finance/cash-flow'
      path: '/finance/cash-flow'
      fullPath: '/finance/cash-flow'
      preLoaderRoute: typeof AuthenticatedFinanceCashFlowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/subscription-plans': {
      id: '/_authenticated/admin/subscription-plans'
      path: '/admin/subscription-plans'
      fullPath: '/admin/subscription-plans'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/price-lists': {
      id: '/_authenticated/admin/price-lists'
      path: '/admin/price-lists'
      fullPath: '/admin/price-lists'
      preLoaderRoute: typeof AuthenticatedAdminPriceListsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payment-methods': {
      id: '/_authenticated/admin/payment-methods'
      path: '/admin/payment-methods'
      fullPath: '/admin/payment-methods'
      preLoaderRoute: typeof AuthenticatedAdminPaymentMethodsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/lead-sources': {
      id: '/_authenticated/admin/lead-sources'
      path: '/admin/lead-sources'
      fullPath: '/admin/lead-sources'
      preLoaderRoute: typeof AuthenticatedAdminLeadSourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/income-categories': {
      id: '/_authenticated/admin/income-categories'
      path: '/admin/income-categories'
      fullPath: '/admin/income-categories'
      preLoaderRoute: typeof AuthenticatedAdminIncomeCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/groups': {
      id: '/_authenticated/admin/groups'
      path: '/admin/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AuthenticatedAdminGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/expense-categories': {
      id: '/_authenticated/admin/expense-categories'
      path: '/admin/expense-categories'
      fullPath: '/admin/expense-categories'
      preLoaderRoute: typeof AuthenticatedAdminExpenseCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/email-templates': {
      id: '/_authenticated/admin/email-templates'
      path: '/admin/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AuthenticatedAdminEmailTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/discounts': {
      id: '/_authenticated/admin/discounts'
      path: '/admin/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AuthenticatedAdminDiscountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/contract-templates': {
      id: '/_authenticated/admin/contract-templates'
      path: '/admin/contract-templates'
      fullPath: '/admin/contract-templates'
      preLoaderRoute: typeof AuthenticatedAdminContractTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/branches': {
      id: '/_authenticated/admin/branches'
      path: '/admin/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AuthenticatedAdminBranchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/children/': {
      id: '/_authenticated/clients/children/'
      path: '/clients/children'
      fullPath: '/clients/children/'
      preLoaderRoute: typeof AuthenticatedClientsChildrenIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/children/$id': {
      id: '/_authenticated/clients/children/$id'
      path: '/clients/children/$id'
      fullPath: '/clients/children/$id'
      preLoaderRoute: typeof AuthenticatedClientsChildrenIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffIdRoute: typeof AuthenticatedStaffIdRoute
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffIdRoute: AuthenticatedStaffIdRoute,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
  AuthenticatedAdminBranchesRoute: typeof AuthenticatedAdminBranchesRoute
  AuthenticatedAdminContractTemplatesRoute: typeof AuthenticatedAdminContractTemplatesRoute
  AuthenticatedAdminDiscountsRoute: typeof AuthenticatedAdminDiscountsRoute
  AuthenticatedAdminEmailTemplatesRoute: typeof AuthenticatedAdminEmailTemplatesRoute
  AuthenticatedAdminExpenseCategoriesRoute: typeof AuthenticatedAdminExpenseCategoriesRoute
  AuthenticatedAdminGroupsRoute: typeof AuthenticatedAdminGroupsRoute
  AuthenticatedAdminIncomeCategoriesRoute: typeof AuthenticatedAdminIncomeCategoriesRoute
  AuthenticatedAdminLeadSourcesRoute: typeof AuthenticatedAdminLeadSourcesRoute
  AuthenticatedAdminPaymentMethodsRoute: typeof AuthenticatedAdminPaymentMethodsRoute
  AuthenticatedAdminPriceListsRoute: typeof AuthenticatedAdminPriceListsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminSubscriptionPlansRoute: typeof AuthenticatedAdminSubscriptionPlansRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
  AuthenticatedFinanceCashFlowRoute: typeof AuthenticatedFinanceCashFlowRoute
  AuthenticatedFinanceContractsRoute: typeof AuthenticatedFinanceContractsRoute
  AuthenticatedFinanceExpensesRoute: typeof AuthenticatedFinanceExpensesRoute
  AuthenticatedFinanceInvoicesRoute: typeof AuthenticatedFinanceInvoicesRoute
  AuthenticatedFinancePaymentsRoute: typeof AuthenticatedFinancePaymentsRoute
  AuthenticatedFinancePayrollRoute: typeof AuthenticatedFinancePayrollRoute
  AuthenticatedFinancePnlRoute: typeof AuthenticatedFinancePnlRoute
  AuthenticatedFinanceSettlementsRoute: typeof AuthenticatedFinanceSettlementsRoute
  AuthenticatedLeadsIdRoute: typeof AuthenticatedLeadsIdRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
  AuthenticatedClientsChildrenIdRoute: typeof AuthenticatedClientsChildrenIdRoute
  AuthenticatedClientsChildrenIndexRoute: typeof AuthenticatedClientsChildrenIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
  AuthenticatedAdminBranchesRoute: AuthenticatedAdminBranchesRoute,
  AuthenticatedAdminContractTemplatesRoute:
    AuthenticatedAdminContractTemplatesRoute,
  AuthenticatedAdminDiscountsRoute: AuthenticatedAdminDiscountsRoute,
  AuthenticatedAdminEmailTemplatesRoute: AuthenticatedAdminEmailTemplatesRoute,
  AuthenticatedAdminExpenseCategoriesRoute:
    AuthenticatedAdminExpenseCategoriesRoute,
  AuthenticatedAdminGroupsRoute: AuthenticatedAdminGroupsRoute,
  AuthenticatedAdminIncomeCategoriesRoute:
    AuthenticatedAdminIncomeCategoriesRoute,
  AuthenticatedAdminLeadSourcesRoute: AuthenticatedAdminLeadSourcesRoute,
  AuthenticatedAdminPaymentMethodsRoute: AuthenticatedAdminPaymentMethodsRoute,
  AuthenticatedAdminPriceListsRoute: AuthenticatedAdminPriceListsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminSubscriptionPlansRoute:
    AuthenticatedAdminSubscriptionPlansRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
  AuthenticatedFinanceCashFlowRoute: AuthenticatedFinanceCashFlowRoute,
  AuthenticatedFinanceContractsRoute: AuthenticatedFinanceContractsRoute,
  AuthenticatedFinanceExpensesRoute: AuthenticatedFinanceExpensesRoute,
  AuthenticatedFinanceInvoicesRoute: AuthenticatedFinanceInvoicesRoute,
  AuthenticatedFinancePaymentsRoute: AuthenticatedFinancePaymentsRoute,
  AuthenticatedFinancePayrollRoute: AuthenticatedFinancePayrollRoute,
  AuthenticatedFinancePnlRoute: AuthenticatedFinancePnlRoute,
  AuthenticatedFinanceSettlementsRoute: AuthenticatedFinanceSettlementsRoute,
  AuthenticatedLeadsIdRoute: AuthenticatedLeadsIdRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
  AuthenticatedClientsChildrenIdRoute: AuthenticatedClientsChildrenIdRoute,
  AuthenticatedClientsChildrenIndexRoute:
    AuthenticatedClientsChildrenIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
